## Diabetes Predection using logistic Regression 

In [9]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [10]:
df = pd.read_csv('diabetes.csv')
df.head()

Number of times pregnant  Plasma glucose concentration  \
0                         6                           148   
1                         1                            85   
2                         8                           183   
3                         1                            89   
4                         0                           137   

   Diastolic blood pressure  Triceps skin fold thickness  \
0                        72                           35   
1                        66                           29   
2                        64                            0   
3                        66                           23   
4                        40                           35   

   2-Hour serum insulin  Body mass index  Age     Class  
0                     0             33.6   50  positive  
1                     0             26.6   31  negative  
2                     0             23.3   32  positive  
3                    94             28.1   21  negative  
4                   168             43.1   33  positive

In [11]:
df.describe()

Number of times pregnant  Plasma glucose concentration  \
count                768.000000                    768.000000   
mean                   3.845052                    120.894531   
std                    3.369578                     31.972618   
min                    0.000000                      0.000000   
25%                    1.000000                     99.000000   
50%                    3.000000                    117.000000   
75%                    6.000000                    140.250000   
max                   17.000000                    199.000000   

       Diastolic blood pressure  Triceps skin fold thickness  \
count                768.000000                   768.000000   
mean                  69.105469                    20.536458   
std                   19.355807                    15.952218   
min                    0.000000                     0.000000   
25%                   62.000000                     0.000000   
50%                   72.000000                    23.000000   
75%                   80.000000                    32.000000   
max                  122.000000                    99.000000   

       2-Hour serum insulin  Body mass index         Age  
count            768.000000       768.000000  768.000000  
mean              79.799479        31.992578   33.240885  
std              115.244002         7.884160   11.760232  
min                0.000000         0.000000   21.000000  
25%                0.000000        27.300000   24.000000  
50%               30.500000        32.000000   29.000000  
75%              127.250000        36.600000   41.000000  
max              846.000000        67.100000   81.000000

In [12]:
df.isnull().sum()

Number of times pregnant        0
Plasma glucose concentration    0
Diastolic blood pressure        0
Triceps skin fold thickness     0
2-Hour serum insulin            0
Body mass index                 0
Age                             0
Class                           0
dtype: int64

In [13]:
df = pd.get_dummies(df ,columns=['Class'] , drop_first = True)

In [16]:
df.sample(3)

Number of times pregnant  Plasma glucose concentration  \
132                         3                           170   
481                         0                           123   
524                         3                           125   

     Diastolic blood pressure  Triceps skin fold thickness  \
132                        64                           37   
481                        88                           37   
524                        58                            0   

     2-Hour serum insulin  Body mass index  Age  Class_positive  
132                   225             34.5   30               1  
481                     0             35.2   29               0  
524                     0             31.6   24               0

## Split the data into X and Y independand variable and dependent variable

In [19]:
x = df.iloc[: , :7]
x

Number of times pregnant  Plasma glucose concentration  \
0                           6                           148   
1                           1                            85   
2                           8                           183   
3                           1                            89   
4                           0                           137   
..                        ...                           ...   
763                        10                           101   
764                         2                           122   
765                         5                           121   
766                         1                           126   
767                         1                            93   

     Diastolic blood pressure  Triceps skin fold thickness  \
0                          72                           35   
1                          66                           29   
2                          64                            0   
3                          66                           23   
4                          40                           35   
..                        ...                          ...   
763                        76                           48   
764                        70                           27   
765                        72                           23   
766                        60                            0   
767                        70                           31   

     2-Hour serum insulin  Body mass index  Age  
0                       0             33.6   50  
1                       0             26.6   31  
2                       0             23.3   32  
3                      94             28.1   21  
4                     168             43.1   33  
..                    ...              ...  ...  
763                   180             32.9   63  
764                     0             36.8   27  
765                   112             26.2   30  
766                     0             30.1   47  
767                     0             30.4   23  

[768 rows x 7 columns]

In [20]:
y = df.iloc[:,-1]
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Class_positive, Length: 768, dtype: uint8

In [21]:
# pip install StandardScaler

In [23]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
df_scale = sc.fit_transform(x)
df_scale 



array([[ 0.63994726,  0.84832379,  0.14964075, ..., -0.69289057,
         0.20401277,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.69289057,
        -0.68442195, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -0.69289057,
        -1.10325546, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ...,  0.27959377,
        -0.73518964, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.69289057,
        -0.24020459,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.69289057,
        -0.20212881, -0.87137393]])

In [24]:
from sklearn.model_selection import train_test_split
xtrain , xtest , ytrain , ytest = train_test_split(df_scale , y , test_size = 0.2 ,random_state = 10)
xtrain

array([[-1.14185152,  1.28648383,  0.35643175, ...,  0.17539902,
         2.69162998, -0.70119842],
       [-0.54791859, -1.06080207, -3.57259724, ..., -0.69289057,
        -0.39250768, -0.70119842],
       [-1.14185152,  0.5040552 , -0.05715025, ...,  0.59217802,
        -0.91287659, -1.04154944],
       ...,
       [-0.25095213, -0.15318486,  0.25303625, ...,  0.2188135 ,
        -0.72249772, -0.78628618],
       [-0.84488505, -1.02950492, -2.02166474, ...,  0.16671612,
         2.92008462, -0.61611067],
       [ 0.3429808 , -0.77912776,  0.25303625, ..., -0.11113655,
         0.20401277,  0.83038113]])

In [25]:
len(xtrain) , len(xtest)

(614, 154)

In [26]:
reg_model = LogisticRegression()

In [27]:
reg_model.fit(xtrain ,ytrain)

LogisticRegression()

In [28]:
y_pred = reg_model.predict(xtest)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
      dtype=uint8)

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
accuracy_score(ytest , y_pred)

0.7142857142857143